Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -19,9 +19,6 @@ jobs:
       with:
         fetch-depth: 0 # otherwise will fail to push refs to dest repo
 
-    - name: Setup upterm session
-      uses: lhotari/action-upterm@v1
-
     - name: Install OAIC directory
       run: |
           cd ~/
@@ -151,51 +148,51 @@ jobs:
           curl -L -X POST "http://$KONG_PROXY:32080/appmgr/ric/v1/xapps" --header 'Content-Type: application/json' --data-raw '{"xappName": "ss"}'
           sudo kubectl get pods -A
           
-    # - name: Set up 5G Network
-    #   run: |
-    #       echo ">>> Adding UE1..."
-    #       sudo ip netns add ue1
-    #       echo ">>> Adding UE2..."
-    #       sudo ip netns add ue2
-    #       echo ">>> Adding UE3..."
-    #       sudo ip netns add ue3
-    #       echo ">>> Starting EPC..."
-    #       sudo srsepc & pid_epc=$!
-    #       echo ">>> Getting E2NODE IP..."
-    #       export E2NODE_IP=`hostname  -I | cut -f1 -d' '`
-    #       echo ">>> E2NODE IP is ${E2NODE_IP}"
-    #       export E2NODE_PORT=5006
-    #       echo ">>> Getting E2TERM IP..."
-    #       export E2TERM_IP=`sudo kubectl get svc -n ricplt --field-selector metadata.name=service-ricplt-e2term-sctp-alpha -o jsonpath='{.items[0].spec.clusterIP}'`
-    #        echo ">>> Starting eNB..."
-    #       sudo srsenb --enb.n_prb=50 --enb.name=enb1 --enb.enb_id=0x19B \
-    #         --rf.device_name=zmq --rf.device_args="fail_on_disconnect=true,tx_port0=tcp://*:2000,rx_port0=tcp://localhost:2001,tx_port1=tcp://*:2100,rx_port1=tcp://localhost:2101,id=enb,base_srate=23.04e6" \
-    #         --ric.agent.remote_ipv4_addr=${E2TERM_IP} --log.all_level=warn --ric.agent.log_level=debug --log.filename=enbLog.txt --ric.agent.local_ipv4_addr=${E2NODE_IP} --ric.agent.local_port=${E2NODE_PORT} & pid_enb=$!
-    #       echo ">>> eNB started with pid ${pid_enb}"
-    #       echo ">>> Waiting for RIC state to establish"
-    #       sleep 120
-    #       echo ">>> Starting UE1..."
-    #       sudo srsue --gw.netns=ue1 & pid_ue=$!
-    #       sleep 120
-    #       echo ">>> Starting UE2..."
-    #       sudo srsue --gw.netns=ue2 & pid_ue=$!
-    #       sleep 120
-    #       echo ">>> Starting UE3..."
-    #       sudo srsue --gw.netns=ue3 & pid_ue=$!
-    #       sleep 120
+    - name: Set up 5G Network
+      run: |
+          echo ">>> Adding UE1..."
+          sudo ip netns add ue1
+          echo ">>> Adding UE2..."
+          sudo ip netns add ue2
+          echo ">>> Adding UE3..."
+          sudo ip netns add ue3
+          echo ">>> Starting EPC..."
+          sudo srsepc & pid_epc=$!
+          echo ">>> Getting E2NODE IP..."
+          export E2NODE_IP=`hostname  -I | cut -f1 -d' '`
+          echo ">>> E2NODE IP is ${E2NODE_IP}"
+          export E2NODE_PORT=5006
+          echo ">>> Getting E2TERM IP..."
+          export E2TERM_IP=`sudo kubectl get svc -n ricplt --field-selector metadata.name=service-ricplt-e2term-sctp-alpha -o jsonpath='{.items[0].spec.clusterIP}'`
+           echo ">>> Starting eNB..."
+          sudo srsenb --enb.n_prb=50 --enb.name=enb1 --enb.enb_id=0x19B \
+            --rf.device_name=zmq --rf.device_args="fail_on_disconnect=true,tx_port0=tcp://*:2000,rx_port0=tcp://localhost:2001,tx_port1=tcp://*:2100,rx_port1=tcp://localhost:2101,id=enb,base_srate=23.04e6" \
+            --ric.agent.remote_ipv4_addr=${E2TERM_IP} --log.all_level=warn --ric.agent.log_level=debug --log.filename=enbLog.txt --ric.agent.local_ipv4_addr=${E2NODE_IP} --ric.agent.local_port=${E2NODE_PORT} & pid_enb=$!
+          echo ">>> eNB started with pid ${pid_enb}"
+          echo ">>> Waiting for RIC state to establish"
+          sleep 120
+          echo ">>> Starting UE1..."
+          sudo srsue --gw.netns=ue1 & pid_ue=$!
+          sleep 120
+          echo ">>> Starting UE2..."
+          sudo srsue --gw.netns=ue2 & pid_ue=$!
+          sleep 120
+          echo ">>> Starting UE3..."
+          sudo srsue --gw.netns=ue3 & pid_ue=$!
+          sleep 120
 
-    #       python3 mutli_ue.py
+          python3 mutli_ue.py
 
-    #       echo ">>> Pinging IP address..."
+          echo ">>> Pinging IP address..."
 
-    #       while ! sudo ip netns exec ue1 ping 172.16.0.1 -c3; do echo "UE1 Ping Fail"; done ; echo "UE1 setup completed" ;
-    #       while ! sudo ip netns exec ue1 ping 172.16.0.1 -c3; do echo "UE2 Ping Fail"; done ; echo "UE2 setup completed" ;
-    #       while ! sudo ip netns exec ue1 ping 172.16.0.1 -c3; do echo "UE3 Ping Fail"; done ; echo "UE3 setup completed" ;
+          while ! sudo ip netns exec ue1 ping 172.16.0.1 -c3; do echo "UE1 Ping Fail"; done ; echo "UE1 setup completed" ;
+          while ! sudo ip netns exec ue1 ping 172.16.0.1 -c3; do echo "UE2 Ping Fail"; done ; echo "UE2 setup completed" ;
+          while ! sudo ip netns exec ue1 ping 172.16.0.1 -c3; do echo "UE3 Ping Fail"; done ; echo "UE3 setup completed" ;
 
-    #       echo ">>> 5G Network setup completed"
+          echo ">>> 5G Network setup completed"
 
-    # - name: Testing Secure Slicing xApp
-    #   run: |
-    #       cd ~/oaic/ss-xapp
-    #       sudo chmod +x zmqthreeue.sh
-    #       sudo ./zmqthreeue.sh
+    - name: Testing Secure Slicing xApp
+      run: |
+          cd ~/oaic/ss-xapp
+          sudo chmod +x zmqthreeue.sh
+          sudo ./zmqthreeue.sh
